export enum Board {
    'H8' = 'star',
    'A4' = 'doubleLetter',
    'A12' = 'doubleLetter',
    'C7' = 'doubleLetter',
    'C9' = 'doubleLetter',
    'D1' = 'doubleLetter',
    'D8' = 'doubleLetter',
    'D15' = 'doubleLetter',
    'G3' = 'doubleLetter',
    'G7' = 'doubleLetter',
    'G9' = 'doubleLetter',
    'G13' = 'doubleLetter',
    'H4' = 'doubleLetter',
    'H12' = 'doubleLetter',
    'I3' = 'doubleLetter',
    'I7' = 'doubleLetter',
    'I9' = 'doubleLetter',
    'I13' = 'doubleLetter',
    'L1' = 'doubleLetter',
    'L8' = 'doubleLetter',
    'L15' = 'doubleLetter',
    'M7' = 'doubleLetter',
    'M9' = 'doubleLetter',
    'O4' = 'doubleLetter',
    'O12' = 'doubleLetter',
    'B6' = 'tripleLetter',
    'B10' = 'tripleLetter',
    'F2' = 'tripleLetter',
    'F6' = 'tripleLetter',
    'F10' = 'tripleLetter',
    'F14' = 'tripleLetter',
    'J2' = 'tripleLetter',
    'J6' = 'tripleLetter',
    'J10' = 'tripleLetter',
    'J14' = 'tripleLetter',
    'N6' = 'tripleLetter',
    'N10' = 'tripleLetter',
    'B2' = 'doubleWord',
    'B14' = 'doubleWord',
    'C3' = 'doubleWord',
    'C13' = 'doubleWord',
    'D4' = 'doubleWord',
    'D12' = 'doubleWord',
    'E5' = 'doubleWord',
    'E11' = 'doubleWord',
    'K5' = 'doubleWord',
    'K11' = 'doubleWord',
    'L4' = 'doubleWord',
    'L12' = 'doubleWord',
    'M3' = 'doubleWord',
    'M13' = 'doubleWord',
    'N2' = 'doubleWord',
    'N14' = 'doubleWord',
    'A1' = 'tripleWord',
    'A8' = 'tripleWord',
    'A15' = 'tripleWord',
    'H1' = 'tripleWord',
    'H15' = 'tripleWord',
    'O1' = 'tripleWord',
    'O8' = 'tripleWord',
    'O15' = 'tripleWord',
}

export interface Earning {
    letterPoint: number;
    wordFactor: number;
}
